### PR TITLE
Computational Chemistry tutorial and slides

### PR DESCRIPTION
**Pull request by chrisbarnettster**
Create slides and tutorial for computational chemistry tools.

### CODE REVIEW

**Comment by bgruening** [comment]
This PR is going to the wrong repo?

**Comment by chrisbarnettster** [comment]
> This PR is going to the wrong repo?

I forked from training to compchem and then again.... 🤦‍♂️ 
Should probably refork from training to my repo and do some manual hacking 
any other suggestions?

**Comment by bgruening** [comment]
let me try something

**Comment by bgruening** [comment]
Try this link: https://github.com/galaxyproject/training-material/compare/master...chrisbarnettster:compchem

**Pull request closed without merging**
